/* AUTO-GENERATED by generate-icons.cjs.ts. Do not edit manually. */
import dynamic from "next/dynamic";
import { Skeleton } from "@/components/ui/skeleton";
import type { ComponentType, SVGProps } from "react";

export type SVGIcon = ComponentType<SVGProps<SVGSVGElement>>;

export const iconMap = {
    "add": dynamic(() => import("../../public/assets/images/icon-add.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "archive": dynamic(() => import("../../public/assets/images/icon-archive.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "check": dynamic(() => import("../../public/assets/images/icon-check.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "close": dynamic(() => import("../../public/assets/images/icon-close.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "copy": dynamic(() => import("../../public/assets/images/icon-copy.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "created": dynamic(() => import("../../public/assets/images/icon-created.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "dark-theme": dynamic(() => import("../../public/assets/images/icon-dark-theme.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "delete": dynamic(() => import("../../public/assets/images/icon-delete.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "edit": dynamic(() => import("../../public/assets/images/icon-edit.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "home": dynamic(() => import("../../public/assets/images/icon-home.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "last-visited": dynamic(() => import("../../public/assets/images/icon-last-visited.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "light-theme": dynamic(() => import("../../public/assets/images/icon-light-theme.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "logout": dynamic(() => import("../../public/assets/images/icon-logout.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "menu-bookmark": dynamic(() => import("../../public/assets/images/icon-menu-bookmark.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "menu-hamburger": dynamic(() => import("../../public/assets/images/icon-menu-hamburger.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "pin": dynamic(() => import("../../public/assets/images/icon-pin.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "search": dynamic(() => import("../../public/assets/images/icon-search.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "sort": dynamic(() => import("../../public/assets/images/icon-sort.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "theme": dynamic(() => import("../../public/assets/images/icon-theme.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "unarchive": dynamic(() => import("../../public/assets/images/icon-unarchive.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "unpin": dynamic(() => import("../../public/assets/images/icon-unpin.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "visit-count": dynamic(() => import("../../public/assets/images/icon-visit-count.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
  "visit": dynamic(() => import("../../public/assets/images/icon-visit.svg").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,
} as const;

export function preloadIcon(name: AvailableIconNames) {
  switch (name) {
    case "add": return import("../../public/assets/images/icon-add.svg");
    case "archive": return import("../../public/assets/images/icon-archive.svg");
    case "check": return import("../../public/assets/images/icon-check.svg");
    case "close": return import("../../public/assets/images/icon-close.svg");
    case "copy": return import("../../public/assets/images/icon-copy.svg");
    case "created": return import("../../public/assets/images/icon-created.svg");
    case "dark-theme": return import("../../public/assets/images/icon-dark-theme.svg");
    case "delete": return import("../../public/assets/images/icon-delete.svg");
    case "edit": return import("../../public/assets/images/icon-edit.svg");
    case "home": return import("../../public/assets/images/icon-home.svg");
    case "last-visited": return import("../../public/assets/images/icon-last-visited.svg");
    case "light-theme": return import("../../public/assets/images/icon-light-theme.svg");
    case "logout": return import("../../public/assets/images/icon-logout.svg");
    case "menu-bookmark": return import("../../public/assets/images/icon-menu-bookmark.svg");
    case "menu-hamburger": return import("../../public/assets/images/icon-menu-hamburger.svg");
    case "pin": return import("../../public/assets/images/icon-pin.svg");
    case "search": return import("../../public/assets/images/icon-search.svg");
    case "sort": return import("../../public/assets/images/icon-sort.svg");
    case "theme": return import("../../public/assets/images/icon-theme.svg");
    case "unarchive": return import("../../public/assets/images/icon-unarchive.svg");
    case "unpin": return import("../../public/assets/images/icon-unpin.svg");
    case "visit-count": return import("../../public/assets/images/icon-visit-count.svg");
    case "visit": return import("../../public/assets/images/icon-visit.svg");
    default:
      return Promise.resolve();
  }
}

export type AvailableIconNames = keyof typeof iconMap;
export const iconNames = Object.keys(iconMap) as readonly AvailableIconNames[];
