/* AUTO-GENERATED by icon-names-codegen.ts. Do not edit manually. */
import dynamic from "next/dynamic";
import type { ComponentType, SVGProps } from "react";

export type SVGIcon = ComponentType<SVGProps<SVGSVGElement>>;

export const iconMap = {
    "add": dynamic(() => import("../../public/assets/images/icon-add.svg").then(m => m.default)) as SVGIcon,
  "archive": dynamic(() => import("../../public/assets/images/icon-archive.svg").then(m => m.default)) as SVGIcon,
  "check": dynamic(() => import("../../public/assets/images/icon-check.svg").then(m => m.default)) as SVGIcon,
  "close": dynamic(() => import("../../public/assets/images/icon-close.svg").then(m => m.default)) as SVGIcon,
  "copy": dynamic(() => import("../../public/assets/images/icon-copy.svg").then(m => m.default)) as SVGIcon,
  "created": dynamic(() => import("../../public/assets/images/icon-created.svg").then(m => m.default)) as SVGIcon,
  "dark-theme": dynamic(() => import("../../public/assets/images/icon-dark-theme.svg").then(m => m.default)) as SVGIcon,
  "delete": dynamic(() => import("../../public/assets/images/icon-delete.svg").then(m => m.default)) as SVGIcon,
  "edit": dynamic(() => import("../../public/assets/images/icon-edit.svg").then(m => m.default)) as SVGIcon,
  "home": dynamic(() => import("../../public/assets/images/icon-home.svg").then(m => m.default)) as SVGIcon,
  "last-visited": dynamic(() => import("../../public/assets/images/icon-last-visited.svg").then(m => m.default)) as SVGIcon,
  "light-theme": dynamic(() => import("../../public/assets/images/icon-light-theme.svg").then(m => m.default)) as SVGIcon,
  "logout": dynamic(() => import("../../public/assets/images/icon-logout.svg").then(m => m.default)) as SVGIcon,
  "menu-bookmark": dynamic(() => import("../../public/assets/images/icon-menu-bookmark.svg").then(m => m.default)) as SVGIcon,
  "menu-hamburger": dynamic(() => import("../../public/assets/images/icon-menu-hamburger.svg").then(m => m.default)) as SVGIcon,
  "pin": dynamic(() => import("../../public/assets/images/icon-pin.svg").then(m => m.default)) as SVGIcon,
  "search": dynamic(() => import("../../public/assets/images/icon-search.svg").then(m => m.default)) as SVGIcon,
  "sort": dynamic(() => import("../../public/assets/images/icon-sort.svg").then(m => m.default)) as SVGIcon,
  "theme": dynamic(() => import("../../public/assets/images/icon-theme.svg").then(m => m.default)) as SVGIcon,
  "unarchive": dynamic(() => import("../../public/assets/images/icon-unarchive.svg").then(m => m.default)) as SVGIcon,
  "unpin": dynamic(() => import("../../public/assets/images/icon-unpin.svg").then(m => m.default)) as SVGIcon,
  "visit-count": dynamic(() => import("../../public/assets/images/icon-visit-count.svg").then(m => m.default)) as SVGIcon,
  "visit": dynamic(() => import("../../public/assets/images/icon-visit.svg").then(m => m.default)) as SVGIcon,
} as const;

export type AvailableIconNames = keyof typeof iconMap;
export const iconNames = Object.keys(iconMap) as readonly AvailableIconNames[];
