const fs = require("fs");
const path = require("path");

const ICONS_DIR = path.join(process.cwd(), "public", "assets", "images");
const OUT_FILE = path.join(process.cwd(), "src", "lib", "icon.generated.tsx");

/**
 * Ensure that the directory for the given path exists.
 * @param {string} p File path
 */
function ensureDir(p) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
}

/**
 * Convert a path to use POSIX-style forward slashes.
 * i.e. Windows backslashes to forward slashes
 * @param {string} p Path string
 * @returns {string} POSIX-style path
 */
function toPosix(p) {
  return p.split(path.sep).join("/");
}

/**
 * Get all icon SVG files in the given directory.
 * @param {string} dir Directory path
 * @returns {string[]} Array of icon file paths
 */
function getIcons(dir) {
  if (!fs.existsSync(dir)) return [];
  const files = fs.readdirSync(dir, { withFileTypes: true });
  return files
    .filter((d) => d.isFile() && d.name.startsWith("icon-") && d.name.endsWith(".svg"))
    .map((d) => path.join(dir, d.name));
}

function run() {
  const iconFiles = getIcons(ICONS_DIR);
  const relBase = path.relative(path.dirname(OUT_FILE), ICONS_DIR); // e.g. ../../assets/images
  const relBasePosix = toPosix(relBase); // e.g. ../../assets/images with forward slashes

  const entries = iconFiles.map((abs) => {
    const file = path.basename(abs); // icon-foo.svg
    const name = file.replace(/^icon-/, "").replace(/\.svg$/, ""); // foo
    const importPath = `${relBasePosix}/${file}`;
    return `  "${name}": dynamic(() => import("${importPath}").then(m => m.default), { ssr: true, loading: () => <Skeleton className="size-4" />   }) as SVGIcon,`;
  });

  // This switch is used to preload icons dynamically.
  // avoiding the need to wrap the Icons with Suspense when used because they lazy loaded.
  const preloadSwitch = iconFiles
    .map((abs) => {
      const file = path.basename(abs);
      const name = file.replace(/^icon-/, "").replace(/\.svg$/, "");
      const importPath = `${relBasePosix}/${file}`;
      return `    case "${name}": return import("${importPath}");`;
    })
    .join("\n");

  const content = `/* AUTO-GENERATED by generate-icons.cjs.ts. Do not edit manually. */
import dynamic from "next/dynamic";
import { Skeleton } from "@/components/ui/skeleton";
import type { ComponentType, SVGProps } from "react";

export type SVGIcon = ComponentType<SVGProps<SVGSVGElement>>;

export const iconMap = {
  ${entries.join("\n")}
} as const;

export function preloadIcon(name: AvailableIconNames) {
  switch (name) {
${preloadSwitch}
    default:
      return Promise.resolve();
  }
}

export type AvailableIconNames = keyof typeof iconMap;
export const iconNames = Object.keys(iconMap) as readonly AvailableIconNames[];
`;

  ensureDir(OUT_FILE);
  fs.writeFileSync(OUT_FILE, content);
  console.log(`Wrote ${OUT_FILE} with ${iconFiles.length} icons.`);
}

run();
